<?php
$order = $block->getOrder();
$walletAddress = $this->helper('Fredo\Nexty\Helper\Data')->getConfig('payment/sample_gateway/wallet_address');
$this->helper('Fredo\Nexty\Helper\UpdateDB')->update_nexty_db();
$order_id= $order->getIncrementId();
$order_id_prefix=$block->getUrl('nexty');
$order_total=$order->getGrandTotal();
$order_currency=$order->getOrderCurrencyCode();
$QRtextencode=$this->helper('Fredo\Nexty\Helper\Data')->getQRCode($walletAddress,$order_id,$order_total);

//place_order_in_coin($order_id,$order_total,$order_currency);
//$moduleStatus = $this->helper('Fredo\Nexty\Helper\Data')->getConfig('payment/sample_gateway/wallet_address');
?>
<p><?php echo __('Your order number is: '.$order_id) ?></p>
<p><?php echo __('Your order total is: '.$order_total.$order_currency) ?></p>
<p><?php echo __('Shop wallet address: '.$walletAddress) ?></p>
<p><?php echo __('QRtext: '.$QRtextencode) ?></p>
<p>
  <?php
     echo __("<img src='https://chart.googleapis.com/chart?chs=300x300&cht=qr&chl="
    					.$QRtextencode."&choe=UTF-8' title='Link to Google.com' />" );
  ?>
</p>

<script>
require(['jquery', 'jquery/ui'], function($){
    //your js code here
    $.ajax({
            showLoader: true,
            url: "<?php echo $block->getUrl('ajaxreq/index/ajax');?>",
            data: {
              prefix:"<?php echo $order_id_prefix;?>",
              order_id:<?php echo $order_id;?>
            },
            type: "POST",
           // dataType: 'json'
           }).done(function (data) {
               //alert(data);
               console.log(data);
            });
});
</script>
